### ISSUE TITLE
Scanpy integration

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#102]
Hi Pavlin, have you thought about integrating `openTSNE` into `scanpy`? Scanpy has a smart internal setup where the same kNN graph is used for various downstream analysis tasks such as dimensionality reduction or clustering. AFAIK it uses pynndescent for kNN construction. For dimensionality reduction it supports UMAP and t-SNE and even supports FIt-SNE if it's installed (I think), but then of course FIt-SNE needs to rebuild its own kNN graph. It seems it would be much better to actually use openTSNE that can directly re-use the pre-built kNN graph object.

To be honest, I haven't used scanpy that much myself, but I see it's getting more and more popular in the community. So in the interest of the ecosystem I think it'd be great to transition it to openTSNE. 

I imagine that integrating the core t-SNE should be relatively straightforward. One could then think of implementing some "recipes" from our Nat Comms paper on top of that as additional functions, if the scanpy team is interested in that.

What do you think? I have zero time for it right now due to some looming deadlines but could imagine investing some time into it later in spring.

**Comment by pavlin-policar** [comment]
Hey Dmitry, I haven't really thought about it much, but I do think it would be a great idea. I have used scanpy before, although usually not for visualization and it's very nice to work with. This seems like a great use case for openTSNE, exactly as you said, it will take any pre-existing KNN graph. Also, I noticed that in the latest version of scanpy, they introduce `ingest` functionality, which is exactly what I was doing with the t-SNE transform. Currently, `ingest` supports only UMAP, but extending this should be straightforward to enable adding new samples to existing embeddings with openTSNE. I believe this is something that FIt-SNE does not support.

The recipes are a good idea, I've thought about including these in openTSNE as well, since I generally go for the multiscale approach whenever I do anything and find myself copy-pasting code.

**Comment by dkobak** [comment]
Yes!

Definitely would be great to have `ingest` for UMAP and `ingest` for tSNE. (I am not sure what distance `ingest` is currently using to map across datasets. If it's Euclidean distance then it's not very useful. But maybe it's using correlation distance or something similar.)

I guess we should raise this as issue at the scanpy github and discuss there first, but I don't see why they wouldn't want it :-)

As I said, I'd be happy to help, but definitely not before mid-February. Even though I guess it's much easier for you to do it. I could then try to PR my recipes, but this can (and should) be separate from porting openTSNE itself.

**Comment by pavlin-policar** [comment]
> I guess we should raise this as issue at the scanpy github and discuss there first, but I don't see why they wouldn't want it :-)

Yes, checking if this is something they actually want is something we definitely want to do.

I'm quite busy with a whole range of things myself, but I'll see what I can do. I'll be sure to let you know if I open any PR, and you can take a look when you have the time. If you'd like to work on this yourself, that would be fine with me as well. We'll see who has more time sooner.

**Comment by gokceneraslan** [comment]
There is an open issue on Scanpy github https://github.com/theislab/scanpy/issues/996, if any of you are interested to discuss.

**Comment by dkobak** [comment]
Thanks @gokceneraslan! Are you one of the scanpy developers? Would be great to have your opinion then. I think there are basically three separate things one could do:

1) switch scanpy to using openTSNE for tSNE, using already constructed kNN graph
2) add tSNE support for `ingest` using openTSNE functionality.
3) add some tSNE "recipes" based on https://www.nature.com/articles/s41467-019-13056-x

**Comment by gokceneraslan** [comment]
Hi @dkobak,

I'm simply a contributor, and I'm not talking on behalf of scanpy developers, just to clarify. 

I think it's better to discuss these on scanpy github but in my opinion, these all make sense. We can also keep the old tSNE for backwards compatibility but adding an option like method='opentsne' to sc.tl.tsne would be great. This can be the default in later versions.

**Comment by dkobak** [comment]
Update: I opened a discussion here https://github.com/theislab/scanpy/issues/1233.

**Comment by pavlin-policar** [comment]
The relevant PR is here: https://github.com/theislab/scanpy/pull/1561
