### ISSUE TITLE
Documentation hides all commands -- is this intentional?

### ISSUE THREAD

**Issue by sg-s** [pavlin-policar/openTSNE#107]
##### Expected behaviour

I expect to see the commands in the notebook in the documentation (on https://opentsne.readthedocs.io/en/latest/examples/03_preserving_global_structure/03_preserving_global_structure.html )

##### Actual behaviour

ALl commands hidden, only output shown

##### Steps to reproduce the behavior

See what's on https://opentsne.readthedocs.io/en/latest/examples/03_preserving_global_structure/03_preserving_global_structure.html

and compare to

https://github.com/pavlin-policar/openTSNE/blob/master/docs/source/examples/03_preserving_global_structure/03_preserving_global_structure.rst

(same page)

**Comment by dkobak** [comment]
I also noticed that and found it weird.

**Comment by pavlin-policar** [comment]
No, this is definitely not intentional. There must be some setting I need to set in nbconvert...
