### ISSUE TITLE
Sparse matrix input does not seem to work due to a problem with pynndescent

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#109]
See https://github.com/lmcinnes/pynndescent/issues/95. It works for UMAP probably because UMAP uses `NNDescent` without `query`, but here you do use `query` and so it does not work... Just posting it here so that you are aware of it.

**Comment by dkobak** [comment]
Unfortunately there have been no responses to my pynndescent issue (see link above). I guess for the time being we could make it work in openTSNE by building the index directly with 3*perplexity neighbors and not using query() afterwards. We could do this only for sparse inputs, as a workaround.

What do you think? I could implement that and make a PR. I really want to try openTSNE on some sparse inputs and I need this functionality for that.

**Comment by dkobak** [comment]
Actually I did some quick testing and it seems we should get rid of using query() altogether. Please see this screenshot. 91 neighbors corresponds to perplexity 30. The index uses 15 neighbors by default.

![Screenshot from 2020-03-11 00-36-46](https://user-images.githubusercontent.com/8970231/76368421-7a521080-6330-11ea-9085-20e32348e5f4.png)

It might make sense to do more tests, but note that UMAP is not using query() so it seems reasonable to do the same here.

**Comment by pavlin-policar** [comment]
Ok, this is interesting. So `query` is a lot slower when the number of data points is lower, but comparable to just computing the number of neighbors with 70k data points.

1. This needs to be benchmarked on larger data sets. 70k is really not very much, I often have to run this on much larger data sets, and it's more important to me that it works as fast as possible there, where the difference could be hours.

2. How does this compare to the annoy PR? I think it's time to make systematic benchmarks on data sets of varying size e.g. 1k, 10k, 100k, 1mln and base any decisions based on that.

**Comment by dkobak** [comment]
I agree that further tests would be useful. Do you think you can test it on some data? It can be conveniently done outside of openTSNE, simply by running `NNDescent`, `query()`, and my joblib/Annoy code from the PR. Not sure if you want to run it on one thread or all available threads, this could possibly make a difference too.

**Comment by dkobak** [comment]
There is now some further discussion at https://github.com/lmcinnes/pynndescent/issues/95.

**Comment by dkobak** [comment]
FYI: the pynndescent issue has been closed and it's updated on PyPI already (but not yet on conda-forge).

**Comment by dkobak** [comment]
But there is also this https://github.com/lmcinnes/pynndescent/issues/94, affecting openTSNE as well.

**Comment by pavlin-policar** [comment]
It's good that the issues are being addressed, and we don't really have to do anything here. Once the bugfixes are released, the latest version will automatically be installed when somebody installs openTSNE. With the addition of annoy, this should be less of an issue now as well.

**Comment by pavlin-policar** [comment]
This was apparently fixed in https://github.com/lmcinnes/pynndescent/issues/94 (haven't tested it myself) and should be released soon.
