### ISSUE TITLE
Warning about high variance initialization

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#117]
This is a very minor thing, but when I run the following code:

```
np.random.seed(0)
X = np.random.randn(1000,10)

init = np.random.randn(1000,2)
init = init / np.std(init, axis=0) * 0.0001

Z = TSNE(initialization=init).fit(X)
```

I get the warning 

```
Standard deviation of embedding is greater than 0.0001. Initial embeddings with high variance may have display poor convergence.
```

which feels weird because I explicitly set the std to be 0.0001 in each dimension. Maybe the comparison needs some epsilon.

**Comment by pavlin-policar** [comment]
Sure, makes sense. We can have it tolerate up to 0.01, since that's what I was doing up till a couple of commits ago, and it was working fine.
