### ISSUE TITLE
Implement exact t-SNE

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#120]
We talked about it in some PR comments, but I thought I would post it here, for future reference. Would be great to have exact t-SNE implementation in here. Not quite sure what's the best way to incorporate it into the openTSNE framework... one would need to think a bit about the reasonable architecture first.

**Comment by dkobak** [comment]
This is probably available already by using `PerplexityBasedNN` with exact kNN and n_neighbors=N, and BH with theta=0.

It cannot be defined as a single `TSNE()` call because `n_neighbors` is not in the `TSNE()` API. So one needs to get affinities first.

I haven't checked but I guess it should work.

Not sure what else to do about it (if anything at all).

**Comment by pavlin-policar** [comment]
> This is probably available already by using PerplexityBasedNN with exact kNN and n_neighbors=N, and BH with theta=0.

It's a bit convoluted, but I suppose so.

I'm not really sure what the value of an exact implementation would be, really. Sure, to verify that everything works, or checking what kind of errors the approximations introduce, but that't not something anyone really needs on a regular basis. 

I've thought about this several times, and I think that if we really wanted an exact implementation, more as a scientific curiosity or maybe to show people how simple t-SNE really is, then sure. But then it should go into its own self-contained module e.g. `openTSNE.exact`, or something along those lines, so it's clearly separate from everything else. I'm not against this at all -- I think it might even be a cool thing to have, but it would be way down on my list of priorities.

**Comment by dkobak** [comment]
> But then it should go into its own self-contained module e.g. openTSNE.exact, or something along those lines, so it's clearly separate from everything else.

Hmm. I was rather thinking of an opposite approach, where you would have "exact" modules in the standard openTSNE architecture. Thinking a bit more about it now, it could be `negative_gradient_method='exact'` (in addition to BH and FFT) and `neighbors='exact-dense'` (we already have `exact` but that's not enough because it computes sparse affinities; whereas `exact-dense` would compute dense affinities).

However, I agree that the value of this is questionable. I'd be fine with closing this issue if you prefer.

**Comment by pavlin-policar** [comment]
Yeah, that would be a viable approach that would fit well-ish into the current framework. But I wouldn't want to add that option because it gives the impression that this is something that you might want to do. I don't think you'd ever actually want to do that. So I think it's better that it be separate, so the message is clear "This is not the recommended usage".

I'll keep it open, since I do want to implement this one day, but, like I said, low priority.
