### ISSUE TITLE
Save the tsne after fitting data

### ISSUE THREAD

**Issue by wyhhyw123** [pavlin-policar/openTSNE#124]
Can tsne's parameters be saved after fitting data such as lightgbm.save_model()? This may facilitate subsequent batch conversion of data.

**Comment by pavlin-policar** [comment]
Yes, `TSNEEmbedding` objects can be pickled.

If you want the specific parameters used to create the embedding, they are distributed throughout the embedding object, e.g. perplexities should be in `embedding.affinities`, the rest should be in `embedding.gradient_descent_params`. It does not include the number of iterations, momentums, or exaggerations. It may be easier to save the output of `repr(TSNE(...))`

**Comment by wyhhyw123** [comment]
Thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午3:06
收件人:&nbsp;"pavlin-policar/openTSNE"<openTSNE@noreply.github.com&gt;;
抄送:&nbsp;"wyh"<2726475728@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pavlin-policar/openTSNE] Save the tsne after fitting data (#124)





 
Yes, TSNEEmbedding objects can be pickled.
 
If you want the specific parameters used to create the embedding, they are distributed throughout the embedding object, e.g. perplexities should be in embedding.affinities, the rest should be in embedding.gradient_descent_params. It does not include the number of iterations, momentums, or exaggerations. It may be easier to save the output of repr(TSNE(...))
