### ISSUE TITLE
Problems after installing 0.4.0 from source

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#126]
I apologize because it's most likely some mix-up on my side, but I wanted to update to 0.4.0 and something went wrong. Perhaps you'll be able to see what?

I have a local copy of openTSNE, so I pulled the updated source from your repository, thought that I needed to recompile because the C code changed, so I ran `pip install --editable .` (which is how I think I used to install the previous version), and it worked successfully. However, I cannot import openTSNE because of the following error:

```
(sonic) dkobak@lisboa:~/Dropbox/work$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openTSNE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dkobak/Dropbox/work/openTSNE/openTSNE/__init__.py", line 1, in <module>
    from .tsne import TSNE, TSNEEmbedding, PartialTSNEEmbedding, OptimizationInterrupt
  File "/home/dkobak/Dropbox/work/openTSNE/openTSNE/tsne.py", line 11, in <module>
    from openTSNE import _tsne
ImportError: /home/dkobak/Dropbox/work/openTSNE/openTSNE/_tsne.cpython-37m-x86_64-linux-gnu.so: undefined symbol: GOMP_loop_nonmonotonic_guided_next, version GOMP_4.5
>>> 
```

Prior to update to 0.4.0 everything worked fine... I tried uninstalling and installing using `python setup.py install` or `python setup.py develop` and all installations run successfully but I'm always getting this strange import error :(

If nothing helps, I will try removing my local copy entirely and installing from conda, once it's up there.

**Comment by dkobak** [comment]
OK, I don't know what it was, but I deleted my whole `openTSNE` folder, pulled everything from upstream again, re-installed and now it seems to work. Weird. Closing.

**Comment by pavlin-policar** [comment]
That seems very strange, I never had any issues... Still, glad you figured it out, and removing everything would indicate that something strange went on inside your installation.
