### ISSUE TITLE
Pynndescent build/query

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#130]
We discussed this before, but I've been playing around with some sparse data now and wanted to report some runtimes.

When using pynndecent, openTSNE runs `build()` with n_neighbors=15 and then `query()` with n_neighbors=3*perplexity. At the same time, Leland said that that's not efficient and the recommended way to use pynndescent is to run `build()` with the desired number of neighbors and then simply take its constructed kNN graph without querying. You said that you ran some benchmarks and found your way to be faster. Here are runtimes I got on `X` that is sparse of size `(100000, 9630)`.

```
nn = NNDescent(X, metric='cosine', n_neighbors=15)      # Wall time: 39 s
nn.query(X, k=15)                                         # Wall time: 1min 57s
nn.query(X, k=90)                                         # Wall time: 3min 21s
nn90 = NNDescent(X, metric='cosine', n_neighbors=90)  # Wall time: 7min 45s
nn90.query(X, k=90)                                     # Wall time: 57min 53s
```

For k=90 it is indeed faster to build with k=15 and then query with k=90, so I can confirm your observation. 

My only suggestion would be to modify the `NNDescent` class so that if the desired `k` is less than some threshold then build is done with `k+1` and then the constructed tree is returned without `query`. We can simply use 15 as the threshold. I did this locally and can PR.

**Comment by pavlin-policar** [comment]
Yes, sure, that's totally fine. 

Just so we're on the same page, in this example that you gave, we need to be comparing the 39s + 3min 21s against the 7min 45s. We can get the nearest neighbors and their distances from the pynndescent object directly if it is built with the required number of neighbors.

If you can submit a PR that would be great.

**Comment by dkobak** [comment]
Yes. However, I have a weirdest bug that I cannot fix so far. That's what I wrote in nearest_neighbors.py:

```
        if k <= 15:
            n_neighbors_build = k + 1
        else:
            n_neighbors_build = 15

        # UMAP uses the "alternative" algorithm, but that sometimes causes
        # memory corruption, so use the standard one, which seems to work fine
        self.index = pynndescent.NNDescent(
            data,
            n_neighbors=n_neighbors_build,
            metric=self.metric,
            metric_kwds=self.metric_params,
            random_state=self.random_state,
            n_trees=n_trees,
            n_iters=n_iters,
            algorithm="standard",
            max_candidates=60,
            n_jobs=self.n_jobs,
        )

        if k <= 15:
            indices, distances = self.index.neighbor_graph
        else:
            indices, distances = self.index.query(data, k=k + 1)
```

This works fine for k>15, but always crashes my kernel whenever k<15. No Python errors, just a sudden kernel krush. I get `munmap_chunk(): invalid pointer` in the terminal output. At the same time, when I copy this exact code into my notebook outside of openTSNE, it works just fine. Driving me nuts.

**Comment by pavlin-policar** [comment]
Yeah, I don't see anything wrong there at all. I would open an issue in `pynndescent`. I did a quick search for `munmap_chunk` errors and it looks like it's related to broken pointers with heap allocations. I have no clue how this might relate to numba, or even how to begin debugging this. You can always try to set up a fresh conda environment and see if it happens there as well. Given that this only occurs if you import openTSNE, it might be the order of imports? Sorry I can't be of much help here.

**Comment by dkobak** [comment]
I located the source of the error. The kernel crush did not happen where I thought it was happening. It happened later when doing `P+P.T` for the affinity matrix. Took me some time to notice why. I raised an issue at pynndescent: https://github.com/lmcinnes/pynndescent/issues/99.

**Comment by pavlin-policar** [comment]
Glad to hear you've located the problem. I don't really see how `P+P.T` could cause that problem? The memory there should be fully managed by python so memory errors should never occur. Does it maybe happen when you call `joint_probabilities_nn`? I'm fairly sure that function doesn't handle -1 values and indexing a C array with -1 could cause something like this.

**Comment by dkobak** [comment]
I swear that this
```
A = affinity.FixedSigmaNN(X, sigma=1e+6, k=15, metric="cosine", n_jobs=1, verbose=1, symmetrize=False)
```
works fine (note that I set `symmetrize=False` here because otherwise it crashed), and then when I run `A.P+A.P.T` in the next notebook cell (and nothing else, just this one line), the kernel crashes. Every time. 

And this does not happen if I insert `indices[indices<0] += indices.shape[0]` after `indices, distances = self.index.neighbor_graph`, so I concluded that it's due to -1 values in `indices`. No idea how exactly.

**Comment by pavlin-policar** [comment]
I think I've managed to crack what your issue is. Since `P` is constructed directly in [`FixedSigmaNN`](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/affinity.py#L497-L504), then I suppose scipy doesn't do any validation that these are indeed valid indices. So if `indices` includes negative values, then any operation on this "broken" matrix will cause a segfault, since it will try to access a C array at index -1.

My code to reproduce:
```
import numpy as np
import scipy.sparse as sp
np.random.seed(0)  # just so we always get the same result
x = sp.random(100, 100).tocsr()
x.indices[:10] = -1
x + x.T
# segmentation fault  ipython
```
Curiously, if I set a single index to -1 it sometimes doesn't crash. But I think this is probably the issue. The easiest fix would be to simply do
```
x.data[x.indices < 0] = 0
x.eliminate_zeros()
```
If this isn't the problem you're having, then I'm out of ideas right now.

**Comment by dkobak** [comment]
Yes, this must be it. 

I think we should wait for Leland to clarify what these -1 values mean, before proceeding.

**Comment by dkobak** [comment]
Okay, so -1 values mean that pynndescent failed to identify some of neighbors (as per warning that it prints). If this happens, UMAP still proceeds with constructing embedding:

> Any -1's are ignored by UMAP, so we just end up with fewer than expected neighbors in those cases. Generally this means those points end up being outliers.

I am not quite sure what's the best way to deal with it in t-SNE. Just to be clear: `query()` results in this case are also bogus.

OpenTSNE should either exit with an error, or somehow ignore those values. Is there an elegant hack of how we can make openTSNE ignore failed neighbors? We could replace all -1 with the index of the point itself, with distance 0. (And print a warning.) Not quite sure what it will do.

**Comment by pavlin-policar** [comment]
I don't think there is any way to trick openTSNE into dealing with that in the current implementation. The most correct thing to do IMO would be to compute the perplexity values on the reduced nearest neighbors. This would mean adding a couple of `if distances[i, j] == -1: continue` to [`compute_gaussian_perplexity `](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/_tsne.pyx#L30-L100) and fixup the resulting `P` matrix in [`compute_gaussian_perpelxities`](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/affinity.py#L383-L408). Implementation-wise, it would be simpler to throw an exception in after the KNN index is built.

I'm not entirely sure what distance=0 would do. It probably wouldn't crash. It would likely just decrease the variance of the gaussian, which you probably wouldn't want to do. Maybe it wouldn't be an issue if it was just a couple of points.

**Comment by dkobak** [comment]
Yeah. Unfortunately in most cases when there are -1 values, all `n_neighbors` values are equal to -1. So reducing the number of nearest neighbors won't help.

FYI I'm looking into this dataset: https://johnhw.github.io/umap_primes/index.md.html. Turns out that pynndescent fails on around 10% of points (!). From the resulting UMAP embedding it seems that these points mostly stay where they were at initialization.

**Comment by dkobak** [comment]
I played around with this a little more.

In the linked issue, Leland wrote that a large number of -1s is expected behaviour on this dataset with cosine metric https://johnhw.github.io/umap_primes/index.md.html.

Just to be clear: the current behaviour of openTSNE does not make sense, because `query()` yields meaningless results for all points for which `pynndescent` failed (i.e. that have -1 in the graph). I can see three options:

1. If pynndescent fails for some points, openTSNE throws an exception and exits. Disadvantage: it won't be able to embed datasets like the prime numbers, where UMAP produces beautiful results.

2. If pynndescent fails for some points, openTSNE has a special treatment downstream, e.g. these points are taken out of the optimization entirely, and just sit at the initialization (which means basically at 0). Disadvantage: requires ad hoc changes downstream.

3. If pynndescent fails for some points, then some hack is applied to indices/distances arrays so that the points do get a special treatment but without any downstream changes. I tried a few things now, and what works reasonably well is to let all "failed" points randomly attract each other (i.e. I'm randomly making them neighbors of each other). This results in the cluster of "failed" points in the final embedding. For this particular dataset this behaviour actually makes a lot of sense because all "failed" points are similarly special in some way (they are prime numbers). Disadvantage: it's a hack. 

I prefer solution 3, but as I wrote -- it's a hack. I made it throw a warning in this case, explaining what is going on, so that at least the users are warned.

What do you think?

**Comment by pavlin-policar** [comment]
First, since the current behavior of our nearest neighbors using pynndescent is wrong and produces meaningless results in these edge cases, the first order of business should be to change the way we call pynndescent. So if I understand correctly if the method fails, `query` will still return some neighbors, but they will be wrong/meaningless. So `query` never returns -1. So this is dead wrong then. So we've got to change it so it won't use `query` but will build the KNNG with the proper number of neighbors. Unfortunately, this will make it slower on larger data sets. I'm not a fan of that, but I don't see any other way.

I don't particularly like 2. because there might well be a cluster at 0.0 in the final embedding, then these random points will get lost somewhere. I don't particularly mind option 3. as long as the warning is very explicit. I think it would actually lead to more stable optimization. If we were to properly incorporate this, then such a point would have no neighbors then it would be attracted to nothing, but repelled by everything. This would (correctly) shoot the point off of the embedding, causing problems. However, 3. would cluster these points together and would produce a cluster of failed points. This would make them very easy to spot and investigate.

I would also make sure to print out the indices of the failed points in the warning, e.g. `failed for points [2, 4, 1, 10, 20]`, so I can directly copy the indices into Python code, and possibly exclude them from the next run if I don't want to deal with them. And this way, I can also immediately check what's going on with these points.

**Comment by dkobak** [comment]
> So if I understand correctly if the method fails, query will still return some neighbors, but they will be wrong/meaningless. So query never returns -1. So this is dead wrong then. So we've got to change it so it won't use query but will build the KNNG with the proper number of neighbors. Unfortunately, this will make it slower on larger data sets. I'm not a fan of that, but I don't see any other way.

I don't think this is needed. We can still construct the index using k=15, just need to check if there are any -1 produced by it. If yes, the subsequent query() results for these points should be discareded.

>  This would (correctly) shoot the point off of the embedding, causing problems. However, 3. would cluster these points together and would produce a cluster of failed points. This would make them very easy to spot and investigate.

I agree.

> I would also make sure to print out the indices of the failed points in the warning, e.g. failed for points [2, 4, 1, 10, 20], so I can directly copy the indices into Python code, and possibly exclude them from the next run if I don't want to deal with them.

What is there is a lot of points? For this prime factorization dataset, I get 10% failed points. It's a lot to print.

Something else: pynndescent with sparse inputs currently breaks with an error for n_jobs>1. Until this if fixed, we could set n_jobs to 1 for pynndescent calls with sparse inputs.

I can submit what I currently have as a PR and we discuss there. It works fine for me.

**Comment by pavlin-policar** [comment]
> I don't think this is needed. We can still construct the index using k=15, just need to check if there are any -1 produced by it. If yes, the subsequent query() results for these points should be discareded.

Yeah, that works too.

> What is there is a lot of points? For this prime factorization dataset, I get 10% failed points. It's a lot to print.

Hmm, I would prefer to have it show the indices all the time, but you've got like a couple of million numbers, right? Maybe a good middle ground would be to print out the indices only if `verbose=True` and just show the warning when `verbose=False`. It should also indicate that we can set `verbose=True` to get the indices. I think we should make it as easy as possible for someone to go look at the problematic points and the simplest way I can think of is to just dump out the indices.

> Something else: pynndescent with sparse inputs currently breaks with an error for n_jobs>1. Until this if fixed, we could set n_jobs to 1 for pynndescent calls with sparse inputs.

Yeah, I suppose. But again, a warning would be nice. I dislike things like this...

> I can submit what I currently have as a PR and we discuss there.

That would be great.
