### ISSUE TITLE
Limit max_step_norm

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#132]
I'd like to open a discussion about the `max_step_norm` parameter that we introduced into the last release of FIt-SNE as a hack after George came up with an example where some points were shooting off very fast.

Since then, I ran into two other situations where the same thing happened in openTSNE. One example was running some experiments with very large exaggeration factor (30) and learning rate set to N/30. Some points were shooting off. Another example I had right now, using sparse data and cosine metric. I only had N=10000 so I ran Barnes-Hut and saw that several points ended up ~1000 distance away from the main embedding. Of course FFT just got stuck.

I inserted the following lines before `embedding += update` and it seems to have eliminated these issues:

```
            # clip the step sizes
            max_step_norm = 5
            update_norms = np.linalg.norm(update, axis=1, keepdims=True)
            norm_exceeded = update_norms.squeeze() > max_step_norm
            update[norm_exceeded] /= update_norms[norm_exceeded]
            update[norm_exceeded] *= max_step_norm
```

Also, I noticed UMAP does a very similar clipping of the step sizes (I assume for similar reasons).

You currently have `max_grad_norm` which is sensible, but the gradient later gets modified by the gains, momentum, and learning rate. On reflection, I think that limiting the `update` norms makes more sense than limiting the `gradient` norms.

**Comment by pavlin-policar** [comment]
Oh, I had forgotten to include that. I remember we discussed this. Sorry about that.

**Comment by dkobak** [comment]
Back when we discussed it it felt like a curiosity that George stumbled upon, but I am now thinking it may naturally arise, e.g. with high-dimensional sparse data if one analyzes it directly. This fits to George's example that was not sparse but was also high-dimensional.

I could prepare a PR. Should `max_step_norm` be available via API or directly built-in? (e.g. UMAP does not allow to control via API). I'd say yes it should. If yes, should it be turned on by default? I would suggest so. Having both `max_grad_norm` and `max_step_norm` might be excessive, but won't really hurt anything either. And `max_grad_norm=None` by default anyway.

**Comment by pavlin-policar** [comment]
> Should max_step_norm be available via API or directly built-in?

I don't see anything wrong with it being public, but using a sensible default. Almost no one will ever touch this anyways.

> Having both max_grad_norm and max_step_norm might be excessive.

I agree, but it's in the public API, so we can't just remove it. If we wanted to, we could raise deprecation warnings, but I don't really see the point. I'm fine with them both being in.
