### ISSUE TITLE
Question about progress visualization

### ISSUE THREAD

**Issue by senovr** [pavlin-policar/openTSNE#137]
Hi, 
Sometimes, for visualization purposes, it may be beneficial to see how final representation evolves through gradient descend.

Is there any way to extract these intermediate representations?

Thanks

**Comment by pavlin-policar** [comment]
Certainly! There are two ways you can do this. You can either use the `.optimize` API and call that multiple times with a small number of iterations, or use the callback system, which was designed for things like this. I have an [example notebook](https://github.com/pavlin-policar/openTSNE/blob/master/examples/05_animation.ipynb) which generates an animation of the optimization process. The important parameters here are `callbacks=...` and `callbacks_every_iters=`.
