### ISSUE TITLE
FutureWarning/AttributeError for parameter neighbors

### ISSUE THREAD

**Issue by VGalata** [pavlin-policar/openTSNE#139]
First of all, thank you for the great package!

Because I used `warnings.filterwarnings('error')` I ran into an issue which might become problematic in the future.
I am not sure whether it has an impact on the results in the current version of the package.

#### Issue description

The attribute `neighbors` in the `TSNE` class is not set because the parameter `neighbors` are saved into the attribute `neighbors_method`: [see here](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/tsne.py#L1160).
However, the attribute `neighbors` is expected and `scikit-learn` raises a warning which will become an error in version `2.24`:
```
From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
```

#### Steps to reproduce the behavior

The warning can be raised with the provided example call:
```python
from sklearn import datasets
iris = datasets.load_iris()
x, y = iris["data"], iris["target"]
from openTSNE import TSNE
embedding = TSNE(verbose=True).fit(x)
```

Used `conda` environment:
```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - joblib=0.16.0=py_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_14
  - libgfortran-ng=7.5.0=hdf63c60_14
  - libgomp=9.3.0=h24d8f2e_14
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libstdcxx-ng=9.3.0=hdf63c60_14
  - ncurses=6.2=he1b5a44_1
  - numpy=1.19.1=py38h8854b6b_0
  - openssl=1.1.1g=h516909a_1
  - opentsne=0.4.4=py38hbf85e49_0
  - pandas=1.1.0=py38h950e882_0
  - pip=20.2.1=py_0
  - python=3.8.5=h4d41432_2_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - readline=8.0=he28a2e2_2
  - scikit-learn=0.23.2=py38hee58b96_0
  - scipy=1.5.2=py38h8c5af15_0
  - setuptools=49.2.1=py38h32f6830_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=hcee41ef_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1006
```

**Comment by pavlin-policar** [comment]
Thanks for reporting this and tracking down the issue. This comes from the `__repr__` call, and should be trivial to fix. To maintain backward compatibility, we should just add another field called `neighbors`. I assume that should fix the problem. Would you be willing to open a PR with this?
