### ISSUE TITLE
PyNNDescent release candidate

### ISSUE THREAD

**Issue by lmcinnes** [pavlin-policar/openTSNE#140]
Hi,

I wanted to give you notice that I have a new release candidate out for version 0.5 of pynndescent. This involves some largeish changes, and a parameter (``diversify_epsilon``) got renamed (to ``diversify_prob``) as its behaviour changed somewhat. I'm hoping to get things worked out and the new release out properly over the next ew weeks. If you want to verify that the new candidate release will work for you I would appreciate it.

**Comment by pavlin-policar** [comment]
Thanks for the heads up! I've been pretty swamped, but nobody's complained about this yet, so I guess it works :) I don't think we use that parameter, so I think it should be fine.
