### ISSUE TITLE
Post installation issue

### ISSUE THREAD

**Issue by arifmasrur** [pavlin-policar/openTSNE#141]
Hi, using `conda install -c conda-forge opentsne` worked just fine -i.e. `from openTSNE import TSNE` works. I can generate TSNE embeddings. However, for visualizing I need utils, and  `from examples import utils` giving **ModuleNotFoundError: No module named 'examples'** error. 

Why this is happening? Have I missed anything during installation? Thanks.

**Comment by pavlin-policar** [comment]
No, you're not missing anything. You can easily visualize embeddings using matplotlib. After all, `TSNEEmbedding` objects are just 2D numpy arrays. Those example utils are there just for the example notebooks. I don't think they're even packaged in the conda package. If you really want to use the example utils, I suggest you clone the repository from GitHub, and `python setup.py install`. Then it should work I think. But again, those utils are just wrappers around matplotlib, so I suggest using that.
