### ISSUE TITLE
Issue with when using custom metric

### ISSUE THREAD

**Issue by jdtuck** [pavlin-policar/openTSNE#149]
When I set metric to custom callable function I get the following error, ![image](https://user-images.githubusercontent.com/2325587/98390436-97032d00-2012-11eb-8043-c3515596eb4c.png)

Any thoughts?

**Comment by dkobak** [comment]
Yeah, you need the latest version of openTSNE which is not on conda yet. If you install current openTSNE master from Github, you won't have this problem. You can probably also replace the `nearest_neighbors.py` in your installation by the file from Github.

**Comment by jdtuck** [comment]
Okay thanks, will install from source now

**Comment by jdtuck** [comment]
Thanks worked,
