### ISSUE TITLE
pynndescent update warning

### ISSUE THREAD

**Issue by maressyl** [pavlin-policar/openTSNE#151]
Hi,

I ran a fresh `pip` install of openTSNE and got the following warning :
```
/usr/local/lib/python3.8/dist-packages/openTSNE/nearest_neighbors.py:331: UserWarning: `pynndescent` has recently changed which distance metrics are supported, and `openTSNE.nearest_neighbors` has not been updated. Please notify the developers of this change.
```

With the following error (not sure if it is related, I'm fairly new to Python) :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/openTSNE/tsne.py", line 1189, in fit
    embedding = self.prepare_initial(X)
  File "/usr/local/lib/python3.8/dist-packages/openTSNE/tsne.py", line 1235, in prepare_initial
    affinities = PerplexityBasedNN(
  File "/usr/local/lib/python3.8/dist-packages/openTSNE/affinity.py", line 137, in __init__
    self.knn_index, self.__neighbors, self.__distances = build_knn_index(
  File "/usr/local/lib/python3.8/dist-packages/openTSNE/affinity.py", line 319, in build_knn_index
    neighbors, distances = knn_index.build(data, k=k)
  File "/usr/local/lib/python3.8/dist-packages/openTSNE/nearest_neighbors.py", line 394, in build
    self.index = pynndescent.NNDescent(
TypeError: __init__() got an unexpected keyword argument 'algorithm'
```

I am running :
* openTSNE 0.4.4
* pynndescent 0.5.1
* Python 3.8.5
* Ubuntu 20.04.1 LTS (Singularity image)

My code is :

```
import numpy
from openTSNE import TSNE
from openTSNE.callbacks import ErrorLogger

# Parse CSV
cpm = numpy.genfromtxt('out/CPM_0.975.tsv', delimiter='\t', names=True)

# Initialize TSNE model
model = TSNE(
    perplexity = 10,
    metric = "correlation",
    n_jobs = 8,
    random_state = 42,
)

# Run TSNE
tsne = model.fit(cpm)
```

Best,
Sylvain

**Comment by dkobak** [comment]
This is already fixed in the Github version but is unfortunately not on pip/conda yet. You can either download and install from Github, or wait until it's released on pip/conda (but I don't know how long @pavlin-policar), or manually replace `nearest_neighbors.py` in your installation with the Github version. This is the only affected file.

**Comment by maressyl** [comment]
Hi Dmtry,

It works replacing the file you mention with the version in Github, and the error was not related. Thanks a lot !

Best,
Sylvain

**Comment by pavlin-policar** [comment]
I'm going to try to release a new version with the fix in the next few days. I was waiting for Py39 to be available on the Windows VMs on Azure pipelines, where we build our wheels. They're available now. I just have to fix some bug with LLVM that just started popping up.
