### ISSUE TITLE
Cannot pickle an affinity object

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#155]
Affinity objects cannot be pickled, it seems. Sometimes this is pretty inconvenient.

```
import pickle
from openTSNE import affinity
X = np.random.randn(1000,10)
A = affinity.Uniform(X, k_neighbors=15, n_jobs=-1)
pickle.dump(A, open('test.pickle', 'wb'))
```

results in

```
TypeError: can't pickle annoy.Annoy objects
```

Is there anything we can do? As a workaround, openTSNE could at least pickle everything apart from the Annoy object, so that one could run t-SNE on the pickled affinity even if out-of-sample embedding does not work.

**Comment by pavlin-policar** [comment]
> As a workaround, openTSNE could at least pickle everything apart from the Annoy object, so that one could run t-SNE on the pickled affinity even if out-of-sample embedding does not work.

Hmm, I suppose that might be a solution, but it's definitely not great. Ideally, annoy would support pickling, and until they do that, I don't really see much we can do. One way to do it might be to use the annoy saving to disk utilities to write/read the annoy index, but that would mean having two files to worry about, which is not great. I agree that if working with large data, it is annoying to have to re-calculate the KNNG every time. I wouldn't be opposed to this workaround, but it feels more like a band-aid than a real solution.

**Comment by dkobak** [comment]
Personally, I think this would be quite a helpful band-aid.

I have a student working with a huge dataset now, and she would like to pickle the affinity object to be able later to try out several tSNE variants (with various exaggerations and with various dfs) on the same affinity matrix.

You could print a warning when pickling that the Annoy object won't be saved and hence not all functionality will be available after unpickling.

**Comment by pavlin-policar** [comment]
I agree. Until we get this done, I would suggest implementing a custom `Affinity` object, where you can just assign the `P` matrix. The internal scipy sparse matrix is easily picklable, so she can calculate the affinity matrix once, then pickle/load that as needed. That would probably be the easiest way to go.

I'll be quite busy until March since I have to submit my PhD topic proposal by then, so I don't think this is something that will get fixed that soon. Unless you two want to take a stab at it :)

**Comment by dkobak** [comment]
> Unless you two want to take a stab at it :)

Hmm. I am actually not sure how to write a custom pickling function for a class. I think dataframes in Pandas have a `to_pickle` function -- should it be done like that?

**Comment by pavlin-policar** [comment]
The python docs are helpful here: https://docs.python.org/3/library/pickle.html#pickling-class-instances. Basically, implementing. I think it should be a matter of defining `__getstate__` to return everything but the annoy index, maybe adding a flag in the `__setstate__` to indicate when an instance was unpickled and there is no annoy index, and raising some errors if we try to access the knn index. Maybe a possible solution would be to define the knn index as a `property` in unpickled objects which throws an error on access.
