### ISSUE TITLE
Sparse input with cosine metric does not use Pynndescent

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#158]
Sparse input should default to Pynndescent. But it doesn't if the metric is cosine. I don't understand why?

https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/affinity.py#L278

```
preferred_approx_method = nearest_neighbors.Annoy
    if is_package_installed("pynndescent") and sp.issparse(data) and metric not in [
        "cosine",
        "euclidean",
        "manhattan",
        "hamming",
        "dot",
        "l1",
        "l2",
        "taxicab",
    ]:
        preferred_approx_method = nearest_neighbors.NNDescent
```

It's weird but I am actually pretty sure that it used to work correctly. My code that used to work previously does not work anymore. Anyway, what's the reason for this `metric not in` clause?

CC @TimRepke.

**Comment by dkobak** [comment]
Oh @pavlin-policar, I think you might have broken it in https://github.com/pavlin-policar/openTSNE/commit/adf89ab038743586f7ac20ad5e95d723ee8cd399 ;)

**Comment by dkobak** [comment]
It should probably be `if is_package_installed("pynndescent") and (sp.issparse(data) or metric not in [...])`

**Comment by TimRepke** [comment]
I see it the same as Dmitry does. Small logical error. Although, it doesn't explain why it's exclusively on cosine, should actually fail for all the metrics in the list. 

The logic was reverse before the last commit. It used to be the clause for explicitly non-sparse data and checks whether any of the metrics are supported by the default algorithm.

**Comment by pavlin-policar** [comment]
Oh, thanks for uncovering this. A little mistake on my part.
