### ISSUE TITLE
negative_gradient_method='auto'

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#179]
I think we discussed it a few times already without reaching any decision, but people keep asking me why openTSNE is so much slower than sklearnTSNE, and it turns out they have super small sample size of maybe n~100 or so. 

I suggest defaulting to `negative_gradient_method='auto'` with some very simple heuristic, like n<1000 uses `'bh'` and n>=1000 uses `'fft'`. The optimal threshold depends on the hardware, number of threads, etc, so 1000 is not going to be optimal, but I think it's maybe better than using FFT always. What do you think?

This post is motivated by this message I got now:

>  The same code needs ~25s with opentsne but only ~3s with sklearn.

Setting it to BH solved it.

**Comment by pavlin-policar** [comment]
Yeah, I've been thinking of adding this as well in this new range of updates. But I was thinking more along the 10k mark for the threshold. In my very limited experiments (I just ran the macosko data set a few times), 10k seemed like the case where maybe `bh` takes about as long as `fft`.

**Comment by dkobak** [comment]
FWIW here is what I get on my laptop:

![bh-vs-fft](https://user-images.githubusercontent.com/8970231/115145097-43305180-a050-11eb-91a4-1ce2aca1be0d.png)

So for me the crossing point is around 5000 for 1 thread and around 15000 for 8 threads.

**Comment by pavlin-policar** [comment]
Heh, 10k seems like a good middle ground then.

**Comment by dkobak** [comment]
Sounds good.
