### ISSUE TITLE
ErrorLogger in docs

### ISSUE THREAD

**Issue by rumaak** [pavlin-policar/openTSNE#186]
Hope it's ok to post.

Even though `ErrorLogger` is deprecated it is still used in all the examples as shown in docs, for example [here](https://opentsne.readthedocs.io/en/latest/examples/01_simple_usage/01_simple_usage.html). I can see the examples were updated in the repo, so perhaps generating the docs again would solve this?

**Comment by pavlin-policar** [comment]
Yes, of course! Thanks for reporting. It seems I forgot to run the conversion job when updating the docs. I'll fix this ASAP.

**Comment by pavlin-policar** [comment]
Closed in 2877131fa6ad87dbdd1fddca4ea15687b39d3fac
