### ISSUE TITLE
how to get embedding in np.array format

### ISSUE THREAD

**Issue by morningphase** [pavlin-policar/openTSNE#201]
##### what can I do

**Comment by dkobak** [comment]
What about `np.array(low_dim_embs)`?

**Comment by pavlin-policar** [comment]
`TSNEEmbedding` is actually a subclass of `np.ndarray`, so you could treat it as such. If you want to get rid of the extra variables you can do `np.array(low_dim_embs)`, as Dmitry has written, or you could do `low_dim_embs.view(np.ndarray)`.
