### ISSUE TITLE
The docstring on pickling Annoy objects seems to be out of date

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#211]
The docstring here https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/nearest_neighbors.py#L213 (about pickling Annoy objects into a separate file) seems obsolete: that's not the way this is currently done in the code.

**Comment by pavlin-policar** [comment]
Yes, you're right! I guess I forgot to change the docstring when I fixed this behaviour. Thanks for pointing this out.
