### ISSUE TITLE
macosko_2015.pkl.gz file

### ISSUE THREAD

**Issue by 193769981** [pavlin-policar/openTSNE#212]
Thank you for your very good work, very inspiring to me, would like to ask where the macosko_2015.pkl.gz file can be downloaded, thank you!

**Comment by pavlin-policar** [comment]
Thanks for using openTSNE! I was fairly sure I included the link somewhere in the repository, but I can't find it now.

You can download the file from http://file.biolab.si/opentsne/benchmark/macosko_2015.pkl.gz
