### ISSUE TITLE
Numpy incompatibility

### ISSUE THREAD

**Issue by ll-portes** [pavlin-policar/openTSNE#213]
Hi guys, 

I'm using openTSNE for the first time. However, it seems that openTSNE is not compatible with newer versions of Numpy. I don't know if that is an issue, or if I'm supposed to build it on my machine. 

##### Actual behaviour
Get this message when importing anything from openTSNE: 

> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

##### Steps to reproduce the behavior
Openning a Jupyter notebook and running the code:
`from openTSNE import TSNE`

**Remarks**
1. Numpy version  1.21.5  py39h7a5d4dd_2
2. opentsne version     0.6.2    py39h79cecc1_0
3. I read that openTSNE 0.6.2 is build with oldest-supported-numpy. Does it mean I should build it on my machine. I appologize if my rased issue is not really an issue.

**Comment by xheon** [comment]
Hi, I got the same issue. Clone the repo and building it locally resolved the issue for me.

**Comment by pavlin-policar** [comment]
I've seen this error before, but what usually ended up happening is that I installed openTSNE with one version of numpy, but then some package or other decided to up/downgrade numpy in the environment, causing the mismatch. Either way, locally building the package in whatever environment you have should definitely solve the problem.

I'll close for now, but please reopen if you have any further questions.
