### ISSUE TITLE
Missed reference

### ISSUE THREAD

**Issue by rozyangno** [pavlin-policar/openTSNE#219]
I think you missed our paper in your citations.

Zhirong Yang, Jaakko Peltonen and Samuel Kaski. Scalable Optimization of Neighbor Embedding for Visualization. In ICML 2013.

**Comment by pavlin-policar** [comment]
I am not as familiar with the history of how the Barnes-Hut approach for t-SNE was developed, but based on your publication, it seems to me that you guys and van der Maaten concurrently developed the same approach. Is this correct?

**Comment by rozyangno** [comment]
Yes, they were concurrently developed.
