### ISSUE TITLE
Problem with data from CSV file

### ISSUE THREAD

**Issue by sbembenek18** [pavlin-policar/openTSNE#251]
I'm loading my data from CSV and it has the follwowing format:

string, PC1, .......
There's ~50 PCA (PC1 ...) components in all and several thousand rows. 

Here's a sample of the data matrix ==> [Data](https://drive.google.com/file/d/1FMUUHNgGomELJKkK6i3OKbGGu3jGBs1Q/view?usp=sharing)

```
import csv
import numpy as np

# Read data from CSV
data = []
with open('./data.csv', 'r') as f:  
    reader = csv.reader(f)
    for row in reader:
        data.append(row)

data = np.array(data[1:], dtype=str)
X = data[:, 1:]

tsne = TSNE(
    perplexity=24.33,
    metric="euclidean",
    n_jobs=8,
    random_state=42,
    verbose=True,
)

X_2d = tsne.fit(X) # Problem here
```
I'm able to get this work with sklearn TSNE -- is the format for OpenTSNE different? 

thanks!

**Comment by sbembenek18** [comment]
I agree - there's something I am missing. 

I've reworked it using pandas and have tried 3 different data sets. I can only get Open TSNE to work with 1 of the 3 sets, which sklearn TSNE works with all 3 sets. I suspect I ma missing something here. To be sure, I was able to get the example sets to run with Open TSNE. I've attached the code and data sets. 


[tsne_pandas_version_v0.ipynb.tar.gz](https://github.com/pavlin-policar/openTSNE/files/12705827/tsne_pandas_version_v0.ipynb.tar.gz)

[DataSets.tar.gz](https://github.com/pavlin-policar/openTSNE/files/12705828/DataSets.tar.gz)

**Comment by pavlin-policar** [comment]
Could you please paste the code and the error you're getting here on GH?

**Comment by sbembenek18** [comment]
```
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE 

data = pd.read_csv('./data_full_set_10_clusters_35_pca.csv')

from openTSNE import TSNE

tsne = TSNE(
    perplexity=24.33,
    metric="euclidean",
    n_jobs=8,
    random_state=42,
    verbose=True,
)

tsne_result = tsne.fit(data.iloc[:,1:]) # Error here

data[['x','y']] = tsne_result

target_names = data['Cluster'].unique()

#Plot
colors = 'r', 'g', 'b', 'c', 'm', 'y', 'k', 'gray', 'orange', 'purple'
fig, ax = plt.subplots(figsize=(8, 6))
for color, label in zip(colors, target_names):
    selected = data[data.Cluster.eq(label)]
    ax.scatter(x='x', y='y', data=selected, c=color, label=label)
ax.legend(bbox_to_anchor=(1, 0.5), loc='center left', frameon=False)
plt.show()
```

**Comment by sbembenek18** [comment]
What I am finding is that for great than 999 rows, I get the error. Here's two more data set to check with, one with 999 rows (works) and another with 1000 (error). 

[data_1000_records_10_clusters_35_pca.csv](https://github.com/pavlin-policar/openTSNE/files/12706200/data_1000_records_10_clusters_35_pca.csv)


[data_999_records_10_clusters_35_pca.csv](https://github.com/pavlin-policar/openTSNE/files/12706201/data_999_records_10_clusters_35_pca.csv)

**Comment by pavlin-policar** [comment]
This seems to be related to pandas. See https://github.com/pavlin-policar/openTSNE/issues/182.

If this is indeed the case, you can simply extract the numpy matrix from the pandas dataframe like so
```
tsne_result = tsne.fit(data.iloc[:,1:].values)
```

This is technically not a bug, since openTSNE doesn't officially support pandas dataframes. I didn't want to drag that dependency into the requirements, and the solution is simply to use `.values` instead.

**Comment by sbembenek18** [comment]
Yes, I can confirm this solves it (and agree this is not a bug in OpenTSNE). Thanks!

**Comment by sbembenek18** [comment]
Yes, I can confirm this solves it (and agree this is not a bug in OpenTSNE). Thanks!
