### ISSUE TITLE
import errer

### ISSUE THREAD

**Issue by xqfJohn** [pavlin-policar/openTSNE#253]
![image](https://github.com/pavlin-policar/openTSNE/assets/84269762/0df9bdae-6823-4b4f-9891-9933e1ad26f1)

is it a error related to opentsne?

**Comment by pavlin-policar** [comment]
Duplicate of #250.

Tl;dr: you need to run the jupyter server from the `examples` folder so that the folder gets added to the python path. You can also do this manually if you want.
