### ISSUE TITLE
Zeisel18 colors

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#26]
Just in case you want to use the same colours as Zeisel et al. use in their Figure 1, then here they are (I grabbed them from their figure):

```
{'Astroependymal cells': '#d7abd4',
 'Cerebellum neurons': '#2d74bf',
 'Cholinergic, monoaminergic and peptidergic neurons': '#9e3d1b',
 'Di- and mesencephalon neurons': '#3b1b59',
 'Enteric neurons': '#1b5d2f',
 'Hindbrain neurons': '#51bc4c',
 'Immature neural': '#ffcb9a',
 'Immune cells': '#768281',
 'Neural crest-like glia': '#a0daaa',
 'Oligodendrocytes': '#8c7d2b',
 'Peripheral sensory neurons': '#98cc41',
 'Spinal cord neurons': '#c52d94',
 'Sympathetic neurons': '#11337d',
 'Telencephalon interneurons': '#ff9f2b',
 'Telencephalon projecting neurons': '#fea7c1',
 'Vascular cells': '#3d672d'}
```

If you prefer your own colours then no problem, just close this issue :-) But then maybe consider extending the palette such that you get unique colors for each type. Or use a higher level of taxonomy so that you have enough colours for it in your palette.

**Comment by pavlin-policar** [comment]
Thanks for grabbing the colors, I've been meaning to do that for a while.

Regarding the Zeisel data set - we will likely get slightly different embeddings than the ones shown in their paper because they use a KNN-graph weighted adjacency matrix for the affinities as opposed to the distance based affinities we use. Still, your plot has a lot in common with their visualization. Also, their preprocessing pipeline seems pretty involved. 

It's definitely an interesting project.

**Comment by pavlin-policar** [comment]
I've changed the banner image to Macosko - I think it looks nicer. I've included the colors in the notebook utils file.

**Comment by dkobak** [comment]
OK but you shouldn't stretch t-SNE images! A rotation does not change the loss, but horizontal/vertical scaling surely does.

**Comment by pavlin-policar** [comment]
Hehe, I didn't, the stretched look comes from setting the plot size that way. I didn't want the banner image to be too big.

**Comment by dkobak** [comment]
Not sure what you mean -- `figsize` can be anything as long as the x and y scale are equal. You can just shrink it horizontally until the scales are equal.

**Comment by pavlin-policar** [comment]
I mean, yes, from the loss perspective, scaling in one direction surely isn't a good idea, but from a purely visual perspective, does it really matter?

**Comment by dkobak** [comment]
I guess it does not *really* matter :-) but strictly speaking it is not a tSNE solution anymore, so I personally try to avoid stretching. I guess for a banner it's okay (you are optimizing prettiness mainly) but I wouldn't want to see it in a paper.

**Comment by pavlin-policar** [comment]
Well, I rendered it completely square, and I do actually like this more, and it looks even prettier, so I guess you got your way :) It's kind of a shame it I can't center it in the readme. But yeah, I'd be very surprised to find that in a paper :)
