### ISSUE TITLE
setuptools wants to install 'examples' and 'benchmarks' package

### ISSUE THREAD

**Issue by joelb123** [pavlin-policar/openTSNE#37]
Please don't use setuptools.find_packages() in setup.py, as this causes setuptools to want to install packages named 'examples' and 'benchmarks'.  This generally wreaks havoc if fastTSNE isn't installed in a virtual environment.

**Comment by pavlin-policar** [comment]
Thanks for bringing this up, I'll take a look at it ASAP.

**Comment by joelb123** [comment]
diff --git a/setup.py b/setup.py
index 452079d..755f284 100644
--- a/setup.py
+++ b/setup.py
@@ -37,7 +37,7 @@ setup(
     author_email='pavlin.g.p@gmail.com',
     version='0.2.7',
     url='https://github.com/pavlin-policar/fastTSNE',
-    packages=setuptools.find_packages(),
+    packages=['fastTSNE','fastTSNE.pynndescent','fastTSNE._matrix_mul'],
     ext_modules=extensions,
     install_requires=[
         'numpy>1.14',
----
The one-line patch above worked for me.  I note that fastTSNE is now a dependency of Orange 3.18 (https://orange.biolab.si/).

**Comment by pavlin-policar** [comment]
Thanks, I've already pushed a patch to a branch (e7638af) where I'm adding several improvements. I'll merge this as soon as I test this on a mac.

**Comment by pavlin-policar** [comment]
I've released a new version which fixes this. Please note that the package has been renamed to `openTSNE`. It is already available on PyPi, and I've already opened a PR on conda-forge, which I assume will be merged in the next couple of days.
