### ISSUE TITLE
Import Aborted ( Double free or corruption) 

### ISSUE THREAD

**Issue by sajithqburst** [pavlin-policar/openTSNE#49]
##### Actual behaviour
Shows below error.

> double free or corruption (top)
> Aborted
> 

##### Steps to reproduce the behavior
On shell :` pip3 install  openTSNE
`
python>> `import openTSNE`

**Comment by pavlin-policar** [comment]
Could you please provide more information about your system e.g. which operating system you're using, Python version, package versions (`pip freeze`), etc.

**Comment by sajithqburst** [comment]
On further debug, I found that the issue is caused by Numba. Numba tries to invoke intel svml library, which crashes. The solution was to set NUMBA_DISABLE_INTEL_SVML=1, before using.

Closing the issue as it is not directly related to OpenTSNE.
