### ISSUE TITLE
Allow to vary the t-distribution degree of freedom

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#51]
Hi Pavlin. Have you already seen https://arxiv.org/abs/1902.05804 by any chance? I thought you might be interested to add a `df` parameter to openTSNE. It was really easy to implement it in FIt-SNE so I guess it should be pretty easy here as well. I would even consider doing it myself, but alas, I am _so_ caught in revisions right now (including revising this paper) that I am not sure when I would have time for it...

Anyway, if you don't want to implement it (at least not until our paper is out in some reputable place haha) then it's fine. Do let me know if you have any comments on the preprint though.

**Comment by pavlin-policar** [comment]
Hey Dmitry, yes, I glanced over it a while ago, and it's been on my todo list for some time now. From what I remember, I'd just missing the df parameter in the Cauchy kernel (I remember I never bothered doing that for the FFT version), which should be very straightforward. If you find the time, I'd welcome a PR; I'm pretty busy with my master's thesis right now, so it might be a while before I get around to this. 

> Anyway, if you don't want to implement it (at least not until our paper is out in some reputable place haha) then it's fine. Do let me know if you have any comments on the preprint though.

I'll have to give the paper a proper read, but I'm sure you guys came up with something smart :) I'll let you know once I've gone through it.
