### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ICO19U/opentsne/

### ISSUE THREAD

**Issue by VineethKanaparthi** [pavlin-policar/openTSNE#53]
##### Expected behaviour

Installation should have happened smoothly
##### Actual behaviour

Collecting opentsne
  Downloading https://files.pythonhosted.org/packages/d7/e3/85625dc946ef152717f8b0234740864f6b3e2d2e29cfbd429e9251e2cb9e/openTSNE-0.3.1.tar.gz (822kB)
    100% |████████████████████████████████| 829kB 652kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ICO19U/opentsne/setup.py", line 129, in <module>
        if has_c_library("fftw3"):
      File "/tmp/pip-install-ICO19U/opentsne/setup.py", line 39, in has_c_library
        with tempfile.TemporaryDirectory(dir=".") as directory:
    AttributeError: 'module' object has no attribute 'TemporaryDirectory'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ICO19U/opentsne/

##### Steps to reproduce the behavior

pip3 install opentsne
or pip3 install fasttsne

**Comment by pavlin-policar** [comment]
Which version of python are you using? The supported versions are 3.6 and higher. And also, could you please check if the same happens with `opentsne=0.3.0`, I just released 0.3.1 about an hour ago, but really, the error you're getting seems completely unrelated to the latest release.

**Comment by VineethKanaparthi** [comment]
Hi pavlin. My bad My version is 3.5. 
I'm sure it is not related to the new release.
Thank you.

**Comment by pavlin-policar** [comment]
Glad to hear it! Just a heads-up, I seem to have broken something in v0.3.1, am releasing a fix asap.
