### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by xiangruyimoxiaoyangyang** [pavlin-policar/openTSNE#61]
Hi Pavlin! Sorry to bother you again! I use the 01_simple_usage.ipynb,but i meet a mistake
Iteration  450, KL divergence  0.6179, 50 iterations in 0.3072 sec
Iteration  500, KL divergence  0.6173, 50 iterations in 0.3070 sec
Iteration  550, KL divergence  0.6176, 50 iterations in 0.3243 sec
Iteration  600, KL divergence  0.6177, 50 iterations in 0.3255 sec
Iteration  650, KL divergence  0.6189, 50 iterations in 0.3075 sec
Iteration  700, KL divergence  0.6181, 50 iterations in 0.3076 sec
Iteration  750, KL divergence  0.6168, 50 iterations in 0.4510 sec
Traceback (most recent call last):
  File "/home/shao/PycharmProjects/tf/main1.py", line 175, in <module>
    utils.plot(embedding_train, pred_y, colors=utils.MACOSKO_COLORS)
  File "/home/shao/PycharmProjects/tf/utils.py", line 332, in plot
    for yi in classes
  File "/home/shao/PycharmProjects/tf/utils.py", line 332, in <listcomp>
    for yi in classes
KeyError: 0

Process finished with exit code 1

I respect your answer,thank you!

**Comment by pavlin-policar** [comment]
Are you running this on the *macosko* data set? If so, then please make sure you followed the notebook `prepare_macosko` (or something to that effect). The `y` vector should then contain string entries: *Retinal ganglion cells*, *Rods*, ...

The stack trace seems to indicate that we're looking up key `0` (but the stack trace seems a bit incomplete, a copying error maybe?), which isn't one of the macosko cell types. So, if you are running this on your own data set, you should remove the part of `plot` which says `colors=utils.MACOSKO_COLORS`. This will switch to the default colors.

Hopefully, this fixes the issue. If not, please paste the complete stack trace and the code that's causing the error.

**Comment by xiangruyimoxiaoyangyang** [comment]
Thanks,Pavlin!  I had solved my problem . Because I used my own data set ,So I took your advice, I removed the part of plot which says colors = .....  thank you !
