### ISSUE TITLE
Fix PC signs when using PCA initialization

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#69]
I find it very convenient to have some convention for fixing PC signs, when using PCA initialization. I usually fix them such that the sum of eigenvector values is positive (of course some other conventions could work equally well). My suggestion is to insert this snippet

```
# fix PC signs
flipSigns = np.sum(pca_.components_, axis=1) < 0
embedding[:, flipSigns] *= -1
```

in here https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/initialization.py#L57.

By the way, why not add `svd_solver='auto'` parameter to `initialization.pca()` and pass it into the sklearn `PCA` call? Could be convenient IMHO.

**Comment by pavlin-policar** [comment]
Isn't this already deterministic? scikit-learn's PCA calls [`svd_flip`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/extmath.py#L482) everywhere, which

>Adjusts the columns of u and the rows of v such that the loadings in the
    columns in u that are largest in absolute value are always positive.

This is called in every branch of their PCA ([here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/pca.py#L519), [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/pca.py#L440) and [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/extmath.py#L346-L351))

> By the way, why not add `svd_solver='auto'` parameter to `initialization.pca()` and pass it into the sklearn PCA call?

I'd have nothing against that.

**Comment by dkobak** [comment]
Oh wow. I wasn't aware that scikit-learn does that. My apologies. I'm closing this.
