### ISSUE TITLE
Sdist does not include *.pxd

### ISSUE THREAD

**Issue by cgohlke** [pavlin-policar/openTSNE#90]
The source distribution `openTSNE-0.3.9.tar.gz` on [PyPI](https://pypi.org/project/openTSNE/#files) is missing `.pxd` files, such that installing from source fails:

```
Compiling openTSNE/_matrix_mul/matrix_mul_numpy.pyx because it changed.
[1/4] Cythonizing openTSNE/_matrix_mul/matrix_mul_numpy.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# cython: wraparound=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: warn.undeclared=True
# cython: language_level=3
cimport openTSNE._matrix_mul.matrix_mul
       ^
------------------------------------------------------------

openTSNE\_matrix_mul\matrix_mul_numpy.pyx:7:8: 'openTSNE\_matrix_mul\matrix_mul.pxd' not found
```

**Comment by pavlin-policar** [comment]
You're entirely right, the sdist is messed up... It's also missing the cythonized "C" files. This was the first release I made using Azure pipelines, so now there are wheels for every platform, but clearly, somethings going wrong there. I'll look into it ASAP. Thanks for pointing this out.

**Comment by pavlin-policar** [comment]
I've made a new release v0.3.10, where the source distribution seems to be ok, i.e. it contains all the files.
