### ISSUE TITLE
Why 3-dimension embedded space is not supported?

### ISSUE THREAD

**Issue by cp10000** [pavlin-policar/openTSNE#99]
##### Expected behaviour
t-SNE is good for 1, 2 and 3,  (support for dimension 3 must be supported)
##### Actual behaviour
Open-t-sne only support 1, 2
##### Steps to reproduce the behavior

**Comment by pavlin-policar** [comment]
While it is theoretically possible to use t-SNE for any number of dimensions, I have 2 issues with this:

1. the interpolation approximation that makes t-SNE so fast does not scale well to multiple dimensions. The time complexity is actually exponential in the number of dimensions, while still being linear in the number of data points. It's definitely possible, but it would probably be pretty slow. The Barnes-Hut approximation would also take a performance hit, but probably not as much, but that scales O(N log N).
2. plotting things in 3-d is almost never a good idea. These plots are difficult to inspect, you can't print them on paper, and I suspect, leads to overinterpreting t-SNE plots even more than usual.

This is not something I will be adding in the foreseeable future, and, if you really want 3d t-SNE plots, I believe scikit-learn supports up to 3 dimensions.

**Comment by dkobak** [comment]
By the way, have you seen this: https://arxiv.org/pdf/1906.05582.pdf? Skip directly to section III. They somehow implement the repulsive computations of FIt-SNE such that they work for 3d reasonably fast.
It's in Figure 6. See also here

http://t-sne-pi.cs.duke.edu/
https://joss.theoj.org/papers/10.21105/joss.01577
https://github.com/fcdimitr/sgtsnepi

That said, I agree with you that 3D plots are rarely useful. In fact, I think they are only useful to make visually impressive spinning visualizations for public talks ;)

**Comment by pavlin-policar** [comment]
Hey Dmitry, no I haven't seen that. I've been focusing more on the bioinformatics side of things in the past few months. I've looked over section 3 and it definitely looks really interesting. It's a shame there's no supplementary material that would go into a bit more detail about their implementation, both the improved QQ and PQ procedures, as they call them. Thanks for sending this, I'll definitely look at it more carefully.
